# Initialising a Tensor

In [1]:
import torch
import numpy as np

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [3]:
my_tensor = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32, device=device, requires_grad=True)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)

## Other initialisation methods

In [4]:
x = torch.empty(size=(3,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [6]:
x1 = torch.zeros((4,4))
x1

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
x2 = torch.rand((3,3))
x2

tensor([[0.7659, 0.8688, 0.4432],
        [0.6222, 0.0130, 0.2534],
        [0.5060, 0.9174, 0.2105]])

In [9]:
x3 = torch.ones((3,3))
x3

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [10]:
x4 = torch.eye(5, 5)
x4

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [11]:
x5 = torch.arange(start=0, end=5, step=1)
x5

tensor([0, 1, 2, 3, 4])

In [12]:
x6 = torch.linspace(start=0.1, end=1, steps=10)
x6

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [13]:
x7 = torch.empty(size=(1,5)).normal_(mean=0, std=1)
x7

tensor([[ 0.1976, -0.8657,  0.0792, -2.2133, -0.1317]])

In [14]:
x8 = torch.empty(size=(1,5)).uniform_(0, 1)
x8

tensor([[0.7966, 0.3497, 0.3141, 0.4473, 0.7341]])

In [15]:
x9 = torch.diag(torch.ones(3))
x9

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

# How to initialise Tensors and convert them to different types

In [16]:
tensor = torch.arange(4)
tensor

tensor([0, 1, 2, 3])

In [17]:
tensor.bool()

tensor([False,  True,  True,  True])

In [18]:
# int16
tensor.short()

tensor([0, 1, 2, 3], dtype=torch.int16)

In [19]:
# int64
tensor.long()

tensor([0, 1, 2, 3])

In [20]:
# float16
tensor.half()

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [21]:
# float32
tensor.float()

tensor([0., 1., 2., 3.])

In [23]:
# float64
tensor.double()

tensor([0., 1., 2., 3.], dtype=torch.float64)

In [26]:
np_array = np.zeros((5, 5))
tensor = torch.from_numpy(np_array)
tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

In [28]:
np_array_back = tensor.numpy()
np_array_back

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Tensor Math & Comparison Operators

In [29]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

In [30]:
# Addition
z1 = torch.empty(3)
torch.add(x, y, out=z1)

tensor([5., 7., 9.])

In [32]:
z2 = torch.add(x, y)
z2

tensor([5, 7, 9])

In [34]:
z = x+y
z

tensor([5, 7, 9])

In [37]:
# Subtraction
z3 = x-y
z3

tensor([-3, -3, -3])

In [39]:
z4 = torch.true_divide(x, y)
z4

tensor([0.2500, 0.4000, 0.5000])

In [40]:
# inplace operations
t = torch.zeros(3)
t.add_(x)            # t+= x
t

tensor([1., 2., 3.])

In [41]:
# Exponentiation
z = x.pow(2)
z

tensor([1, 4, 9])

In [43]:
z = x ** 2
z

tensor([1, 4, 9])

In [45]:
# Simple Comparison
z = x > 2
z

tensor([False, False,  True])

In [48]:
# Matrix Multiplication
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))
x3 = torch.mm(x1, x2)
x3

tensor([[1.8968, 0.7946, 2.0273],
        [2.0852, 1.0814, 1.6239]])

In [50]:
# Matrix exponentiation
m_exp = torch.rand(5, 5)
m_exp.matrix_power(3)
m_exp

tensor([[0.6112, 0.8072, 0.8039, 0.5792, 0.6227],
        [0.5815, 0.5623, 0.0840, 0.3630, 0.0011],
        [0.5757, 0.1789, 0.7750, 0.8946, 0.6139],
        [0.7754, 0.4802, 0.9340, 0.6495, 0.4750],
        [0.9201, 0.0405, 0.0181, 0.8076, 0.7841]])

In [51]:
# Element wise Multiplication
z = x*y
z

tensor([ 4, 10, 18])

In [53]:
# Dot product
z = torch.dot(x, y)
z

tensor(32)

In [5]:
# Batch Matrix Multiplication
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2)
out_bmm

tensor([[[3.0615, 4.2998, 3.3709,  ..., 4.3521, 4.1220, 4.3401],
         [4.8298, 4.7672, 4.6999,  ..., 5.6536, 4.8190, 5.2032],
         [4.4601, 4.9951, 3.8703,  ..., 5.1444, 4.2015, 5.5168],
         ...,
         [4.0399, 4.2328, 4.0424,  ..., 4.2419, 5.0543, 4.4319],
         [4.9096, 5.5916, 4.5068,  ..., 5.9851, 4.8679, 5.7650],
         [3.4859, 4.7127, 4.0158,  ..., 5.0273, 4.2789, 4.7552]],

        [[5.1463, 4.9462, 4.4588,  ..., 4.8036, 3.7712, 4.2941],
         [5.6989, 5.3808, 5.8268,  ..., 6.2312, 4.8188, 5.2014],
         [4.3863, 4.2134, 4.4704,  ..., 4.3334, 3.7997, 3.1047],
         ...,
         [6.7415, 5.2106, 6.4118,  ..., 5.6936, 5.6106, 5.7763],
         [4.2649, 4.3471, 4.7926,  ..., 3.9464, 4.3824, 3.8788],
         [4.7781, 5.1620, 5.4044,  ..., 4.5942, 4.7454, 4.5718]],

        [[5.6420, 4.4208, 5.4946,  ..., 5.1168, 5.2046, 4.6091],
         [5.4490, 4.5121, 5.4380,  ..., 4.5343, 5.4145, 4.9796],
         [4.6991, 4.4685, 6.4220,  ..., 4.4940, 5.1517, 5.

## Broadcasting

In [6]:
x1 = torch.rand((5, 5))
x2 = torch.rand((1, 5))

z = x1 - x2
z

tensor([[-0.0048, -0.0425, -0.4186,  0.1767,  0.1976],
        [ 0.0605,  0.1980,  0.0127,  0.0760,  0.0240],
        [ 0.0141,  0.2287, -0.3470,  0.5956,  0.2022],
        [ 0.2990, -0.2184, -0.4200,  0.4356, -0.3202],
        [ 0.0425,  0.6655, -0.0082,  0.3623,  0.1677]])

# Other Tensor Operations

In [8]:
x = torch.rand((1, 5))
x

tensor([[0.3859, 0.5601, 0.1349, 0.0017, 0.6048]])

In [10]:
sum_x = torch.sum(x, dim=0)
sum_x

tensor([0.3859, 0.5601, 0.1349, 0.0017, 0.6048])

In [11]:
val, i = torch.max(x, dim=0)
print(val, i)

tensor([0.3859, 0.5601, 0.1349, 0.0017, 0.6048]) tensor([0, 0, 0, 0, 0])


In [12]:
val, i = torch.min(x, dim=0)
print(val, i)

tensor([0.3859, 0.5601, 0.1349, 0.0017, 0.6048]) tensor([0, 0, 0, 0, 0])


In [14]:
abs = torch.abs(x)
abs

tensor([[0.3859, 0.5601, 0.1349, 0.0017, 0.6048]])

In [ ]:
z = torch.argmax(x, dim=0)
z = torch.argmin(x, dim=0)

In [ ]:
# mean requires float values
mean_x = torch.mean(x.float(), dim=0)
# check equality
z = torch.eq(x, y)

In [18]:
sorted_x, i = torch.sort(x, dim=0, descending=False)
sorted_x

tensor([[0.3859, 0.5601, 0.1349, 0.0017, 0.6048]])

In [ ]:
# All elements in x less than zero will be set to zero
z = torch.clamp(x, min=0, max=10)

In [25]:
x = torch.tensor([1,0,1,1,1], dtype=torch.bool)
# Atleast one value is true
z = torch.any(x)
z

tensor(True)

In [26]:
# No value is False
z = torch.all(x)
z

tensor(False)

# Tensor Indexing

In [27]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))
x

tensor([[0.3040, 0.1854, 0.0696, 0.4198, 0.4260, 0.0698, 0.7541, 0.7813, 0.9509,
         0.1565, 0.3582, 0.0099, 0.8454, 0.1171, 0.8904, 0.2878, 0.5082, 0.8901,
         0.9883, 0.9296, 0.6241, 0.2360, 0.2916, 0.0821, 0.5957],
        [0.5575, 0.4097, 0.3293, 0.8973, 0.8497, 0.5903, 0.2423, 0.7061, 0.5067,
         0.5889, 0.7475, 0.3725, 0.9249, 0.1765, 0.8497, 0.1497, 0.1429, 0.7734,
         0.1206, 0.5194, 0.3683, 0.7046, 0.3144, 0.9558, 0.0480],
        [0.5857, 0.7010, 0.0045, 0.5208, 0.7995, 0.5371, 0.7092, 0.0909, 0.0425,
         0.4059, 0.1748, 0.5883, 0.4196, 0.9030, 0.7075, 0.1137, 0.1527, 0.8003,
         0.8106, 0.6274, 0.9122, 0.4143, 0.8671, 0.4310, 0.7893],
        [0.8648, 0.1016, 0.2804, 0.1204, 0.4958, 0.6324, 0.3643, 0.2698, 0.2007,
         0.2156, 0.7702, 0.4793, 0.1798, 0.3919, 0.3071, 0.1339, 0.0767, 0.8588,
         0.8135, 0.3198, 0.5382, 0.8801, 0.8545, 0.6220, 0.2232],
        [0.2543, 0.0264, 0.3670, 0.0654, 0.1394, 0.6549, 0.4664, 0.4849, 0.0153,
       

In [28]:
print(x[0].shape)

torch.Size([25])


In [29]:
x[2, 0:10]

tensor([0.5857, 0.7010, 0.0045, 0.5208, 0.7995, 0.5371, 0.7092, 0.0909, 0.0425,
        0.4059])

## Fancy Indexing

In [33]:
x = torch.arange(10)
indices = [2, 5, 8]
x[indices]

tensor([2, 5, 8])

In [34]:
x = torch.rand(3 ,5)
rows = torch.tensor( [1, 0] )
col = torch.tensor([4, 0])
x[rows, col]

tensor([0.4317, 0.3079])

## Advanced Indexing

In [36]:
x = torch.arange(10)
x[(x < 2) | (x > 8)]

tensor([0, 1, 9])

In [37]:
x[x.remainder(2) == 0]

tensor([0, 2, 4, 6, 8])

## Useful Operations

In [39]:
torch.where(x > 5, x, x*2)

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])

In [42]:
print(torch.tensor([0,0,1,2,2,3,4]).unique())

tensor([0, 1, 2, 3, 4])


In [43]:
x.ndimension()

1

In [44]:
x.numel()

10

# Tensor Reshaping

In [45]:
x = torch.arange(9)
x_3x3 = x.view(3, 3)
x_3x3

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [47]:
x_3x3 = x.reshape(3, 3)
x_3x3

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [51]:
y = x_3x3.t()
y

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [52]:
y.contiguous().view(9)

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [53]:
x1 = torch.rand((2, 5))
x2 = torch.rand((2, 5))
print(torch.cat((x1, x2), dim=0).shape)

torch.Size([4, 5])


In [64]:
x1

tensor([[0.0866, 0.2029, 0.5991, 0.3621, 0.6379],
        [0.7636, 0.6488, 0.7408, 0.7766, 0.5640]])

In [65]:
x2

tensor([[0.1667, 0.6515, 0.4424, 0.7848, 0.0901],
        [0.5376, 0.6431, 0.1563, 0.5779, 0.8983]])

In [67]:
x3 = torch.cat((x1, x2), dim=0)
x3

tensor([[0.0866, 0.2029, 0.5991, 0.3621, 0.6379],
        [0.7636, 0.6488, 0.7408, 0.7766, 0.5640],
        [0.1667, 0.6515, 0.4424, 0.7848, 0.0901],
        [0.5376, 0.6431, 0.1563, 0.5779, 0.8983]])

In [54]:
print(torch.cat((x1, x2), dim=1).shape)

torch.Size([2, 10])


In [69]:
x4 = torch.cat((x1, x2), dim=1)
x4

tensor([[0.0866, 0.2029, 0.5991, 0.3621, 0.6379, 0.1667, 0.6515, 0.4424, 0.7848,
         0.0901],
        [0.7636, 0.6488, 0.7408, 0.7766, 0.5640, 0.5376, 0.6431, 0.1563, 0.5779,
         0.8983]])

In [55]:
z = x1.view(-1)
z

tensor([0.0866, 0.2029, 0.5991, 0.3621, 0.6379, 0.7636, 0.6488, 0.7408, 0.7766,
        0.5640])

In [56]:
batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(batch, -1)
z

tensor([[1.7505e-01, 6.2633e-01, 6.9927e-01, 1.5837e-01, 7.0649e-01, 7.3102e-01,
         3.5442e-01, 8.2349e-01, 8.5035e-01, 2.8392e-01],
        [8.3127e-01, 7.8704e-01, 5.1140e-01, 5.3939e-01, 6.8811e-01, 1.7492e-01,
         2.4929e-01, 1.3497e-01, 6.6085e-01, 8.7345e-01],
        [3.9332e-01, 7.3131e-02, 7.8414e-03, 2.7250e-01, 1.2342e-01, 7.5531e-01,
         2.2263e-01, 5.4282e-01, 4.6097e-01, 9.7136e-01],
        [3.3078e-01, 9.7206e-02, 4.6354e-01, 5.2608e-01, 9.4658e-01, 3.0643e-01,
         6.7583e-01, 2.6922e-01, 3.3481e-01, 8.4104e-01],
        [6.3739e-01, 3.9737e-01, 8.2626e-01, 7.7399e-01, 7.3860e-01, 2.6156e-02,
         1.1196e-01, 7.3609e-01, 4.6433e-01, 4.1782e-01],
        [9.8749e-01, 5.3546e-01, 4.8787e-01, 6.5022e-01, 1.2730e-03, 1.8751e-01,
         2.2019e-01, 9.0728e-01, 2.2777e-01, 1.8904e-01],
        [4.9463e-01, 8.1907e-01, 9.4180e-01, 4.6595e-01, 3.5497e-01, 4.9821e-01,
         6.3557e-01, 5.1430e-02, 3.4109e-01, 8.0368e-01],
        [2.3557e-01, 1.3755

In [57]:
z = x.permute(0, 2, 1)
z

tensor([[[1.7505e-01, 7.3102e-01],
         [6.2633e-01, 3.5442e-01],
         [6.9927e-01, 8.2349e-01],
         [1.5837e-01, 8.5035e-01],
         [7.0649e-01, 2.8392e-01]],

        [[8.3127e-01, 1.7492e-01],
         [7.8704e-01, 2.4929e-01],
         [5.1140e-01, 1.3497e-01],
         [5.3939e-01, 6.6085e-01],
         [6.8811e-01, 8.7345e-01]],

        [[3.9332e-01, 7.5531e-01],
         [7.3131e-02, 2.2263e-01],
         [7.8414e-03, 5.4282e-01],
         [2.7250e-01, 4.6097e-01],
         [1.2342e-01, 9.7136e-01]],

        [[3.3078e-01, 3.0643e-01],
         [9.7206e-02, 6.7583e-01],
         [4.6354e-01, 2.6922e-01],
         [5.2608e-01, 3.3481e-01],
         [9.4658e-01, 8.4104e-01]],

        [[6.3739e-01, 2.6156e-02],
         [3.9737e-01, 1.1196e-01],
         [8.2626e-01, 7.3609e-01],
         [7.7399e-01, 4.6433e-01],
         [7.3860e-01, 4.1782e-01]],

        [[9.8749e-01, 1.8751e-01],
         [5.3546e-01, 2.2019e-01],
         [4.8787e-01, 9.0728e-01],
         [

In [58]:
x = torch.arange(10)
x.unsqueeze(0)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [59]:
x.unsqueeze(1)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [61]:
x = torch.arange(10).unsqueeze(0).unsqueeze(1)
x

tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [63]:
z = x.squeeze(1)
z

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])